name: Flutter builds

on: workflow_dispatch

jobs:
    build_android:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - uses: actions/setup-java@v2
              with:
                  distribution: "zulu"
                  java-version: "17"
            - uses: subosito/flutter-action@v2
              with:
                  flutter-version: "3.3.10"
            - run: flutter pub get
            - run: flutter pub run build_runner build --delete-conflicting-outputs
            # - run: flutter test
            - run: flutter build apk --release
            - run: flutter build appbundle --release
            - name: Release
              uses: softprops/action-gh-release@v1
              if: startsWith(github.ref, 'refs/tags/')
              with:
                files: |
                    build/app/outputs/flutter-apk/app-release.apk
                    build/app/outputs/bundle/release/app-release.aab

    build_ios:
        runs-on: macos-latest
        steps:
            - uses: actions/checkout@v3
            - uses: subosito/flutter-action@v2
              with:
                  channel: "stable"
                  architecture: x64
            - run: flutter pub get
            - run: flutter pub run build_runner build --delete-conflicting-outputs
            # - run: flutter test
            - run: flutter build ios --release --no-codesign
            - name: Release
              uses: softprops/action-gh-release@v1
              if: startsWith(github.ref, 'refs/tags/')
              with:
                files: /Users/runner/work/habit_tracker/habit_tracker/build/ios/iphoneos/Runner.app.

    build_windows:
        runs-on: windows-latest
        steps:
            - uses: actions/checkout@v3
            - uses: subosito/flutter-action@v2
              with:
                  channel: "stable"
            - run: flutter pub get
            - run: flutter config --enable-windows-desktop
            - run: flutter pub run build_runner build --delete-conflicting-outputs
            - run: flutter build windows --release
            - name: Archive Release
              uses: thedoctor0/zip-release@master
              with:
                type: 'zip'
                filename: HabitTracker-${{github.ref_name}}-windows.zip
                directory: build/windows/runner/Release
            - name: Windows Release
              uses: softprops/action-gh-release@v1
              if: startsWith(github.ref, 'refs/tags/')
              env:
                GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              with:
                files: build/windows/runner/Release/HabitTracker-${{github.ref_name}}-windows.zip
    
    build_linux:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - uses: subosito/flutter-action@v2
              with:
                  channel: "stable"
            - run: |
                  sudo apt-get update -y
                  sudo apt-get install -y ninja-build libgtk-3-dev
            - run: flutter pub get
            - run: flutter config --enable-linux-desktop
            - run: flutter pub run build_runner build --delete-conflicting-outputs
            - run: flutter build linux --release
            - name: Archive Release
              uses: thedoctor0/zip-release@master
              with:
                type: 'zip'
                filename: HabitTracker-${{github.ref_name}}-linux.zip
                directory: build/linux/x64/release/bundle
            - name: Linux Release
              uses: softprops/action-gh-release@v1
              if: startsWith(github.ref, 'refs/tags/')
              env:
                GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              with:
                files: build/linux/x64/release/bundle/HabitTracker-${{github.ref_name}}-linux.zip
    
    build_macosx:
        runs-on: macos-latest
        steps:
            - uses: actions/checkout@v3
            - uses: subosito/flutter-action@v2
              with:
                  channel: "stable"
                  architecture: x64
            - run: flutter pub get
            - run: flutter config --enable-macos-desktop
            - run: flutter pub run build_runner build --delete-conflicting-outputs
            - run: flutter build macos --release
            - name: Archive Release
              uses: thedoctor0/zip-release@master
              with:
                type: 'zip'
                filename: HabitTracker-${{github.ref_name}}-macos.zip
                directory: build/macos/Build/Products/Release
            - name: macOS Release
              uses: softprops/action-gh-release@v1
              if: startsWith(github.ref, 'refs/tags/')
              env:
                GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              with:
                files: build/macos/Build/Products/Release/HabitTracker-${{github.ref_name}}-macos.zip
